### ISSUE TITLE
Missing Node Types

### ISSUE THREAD

**Issue by Sinevia** [vicary/node-red-contrib-stripe#12]
Installed the package but getting an error:

Flows stopped due to missing node types.

    stripe-config
    stripe

**Comment by Sinevia** [comment]
Also getting this:

![image](https://user-images.githubusercontent.com/3450815/129946636-54ce393e-06a9-4b18-8fe2-3fb942d676f0.png)

**Comment by vicary** [comment]
What version of node-red are you using?

I tried to make this compatible with 2.x but their types for TypeScript is not really consistence and some internal API is not even typed. Since the last time I checked, their official site still has documentations for 1.x when it comes to custom nodes like this one.

I had to fallback to 1.x only, or explicitly use `any` and hope for the best.

I would definitely try again if more information is available, would you mind doing some research on this front?

**Comment by Sinevia** [comment]
I solved it for now by removing this node and directly using the API.

**Comment by vicary** [comment]
This node is supposed to safe you from directly working with the SDK, thanks for not contributing.
