### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by therealrobster** [vicary/node-red-contrib-stripe#29]
Hi there,

I've just found node red and want to connect to this stripe node.  I have installed the node, and I have put my credentials in but I'm not sure how to trigger it?  Are there any documentation or tutorials out there on a step by step on how to use it?

Thank you so much.

**Comment by vicary** [comment]
@therealrobster The node requires two inputs:
1. A Stripe function that you selected from the Stripe node, or pass in dynamically via `msg.topic`.
2. The function's content, where it reads from the `msg.payload` in JSON format.

For what payload that you should pass in, you may read https://docs.stripe.com/api.

I would suspect that a lot has changed on Stripe's side since my last publish, feel free chip in if you want to see it updated!

**Comment by therealrobster** [comment]
Thank you.  I am a little lost, I am sorry.  I searched for the stripe node, and found it here:
![node](https://github.com/vicary/node-red-contrib-stripe/assets/15485920/d268fa90-948e-4361-90a2-84b3fa5662fa)

I then added it to a blank workflow, double clicked it, added my real, working credentials, and selected a function:
![stripe 1](https://github.com/vicary/node-red-contrib-stripe/assets/15485920/413cfe5b-c489-4a80-a09c-2963065058ec)

At this point though, it has no input or output, so am unsure on how to test it.  I know this is a newby question, and maybe i need to learn more Node Red, but I have been using N8N for some time, and thought it would be similar.  Any pointes appreciated, but understand if you're busy.  Thank you

**Comment by vicary** [comment]
See the grey dots on the left and right side of the node?

The left dot is input and the right dot is output, you can link different nodes through the Stripe node.

To test it, you may try
1. Select the token create function in Stripe node.
2. Drag an inject node, double click and add a payload in JSON format, enter your card number, expiry date and CVV.
3. Drag the right dot of inject node to the left dot of Stripe node.
4. Drag a debug node and connect it to the output side of the Stripe node.
5. Optionally, drag an Error code and place it anywhere because it capture all errors in  the same board. Then connect it to a debug node. This way you can see Stripe API errors if your JSON payload is incorrect.


I think you can start expanding the idea into more workflows from there.

**Comment by therealrobster** [comment]
Thank you, that is helpful.  OK, I was hoping to use it as a trigger.  So, when a new customer is created.   Then, on new customer creation, I can do whatever is requried with the data stripe gives me.

 I see it's in the list of methods of the node, but does that mean I need to manually check that, or perhaps use a webhook?  I don't want to waste your time here, but I have searched long and hard, and can't find much info on this for node red.  N8N is packed with info, but I really want to give Node Red a good try.

**Comment by vicary** [comment]
If your customers are registered via Node RED, you connect an HTTP-in node into Stripe, then ends with an HTTP-out response.

You only need to create a web hook on Stripe if you customers are created at Stripe from an external system, you may use an HTTP-in node to receive the web hook event from Stripe and do further actions from there.

**Comment by vicary** [comment]
@therealrobster I'll close the issue for no actionables at the moment, unless you want to chip in for updates 😉

You may still add more comments here for general support, or questions about general usage.
